@startuml Sistema De Reservas Hotel
class Hospede {
    nome: String
    cpf: String
    telefone: String
    email: String
    cadastrarHospede()
    alterarHospede()
    excluirHospede()
}

class Quarto {
    numero: Int
    andar: Int
    categoria: Categoria
    cadastrarQuarto()
    alterarQuarto()
    excluirQuarto()
}

class Categoria {
    nome: String
    descricao: String
    cadastrarCategoria()
    alterarCategoria()
    excluirCategoria()
}

class Reserva {
    dataInicio: Date
    dataFim: Date
    hospede: Hospede
    quarto: Quarto
    cadastrarReserva()
    alterarReserva()
    excluirReserva()
}

class Pagamento {
    valor: Double
    dataPagamento: Date
    reserva: Reserva
    cadastrarPagamento()
    alterarPagamento()
    excluirPagamento()
}

Hospede "1:1" -- "1:n" Reserva: faz >>
Quarto "1:1" -- "1:n" Reserva: possui >>
Categoria "1:1" -- "1:n" Quarto: possui >>
Reserva "1:1" -- "1:1" Pagamento: possui >>

@enduml