@startuml Sistema de Estoque
title Sistema de Estoque
class Produto {
    nome: String
    codigo: String
    preco: Double
    cadastrarProduto()
    alterarProduto()
    excluirProduto()
}

class Fornecedor {
    nome: String
    cnpj: String
    endereco: String
}

class Lote {
    quantidade: Integer
    dataRecebimento: Date
}

class Estoque {
    quantidade: Integer
    produto: Produto
    lote: Lote
}

class ProdutoFornecedor {
    produto: Produto
    fornecedor: Fornecedor
}

Produto "1:1" -- "1:n" Estoque: possui >>
Produto "1:1" -- "1:n" ProdutoFornecedor: possui >>
ProdutoFornecedor "1:1" -- "1:n" Fornecedor: fornece >>
Lote "1:1" -- "1:n" Estoque: possui >>

@enduml